/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.elle.elle_gui.presentation;

import com.elle.elle_gui.admissions.Authorization;
;
import java.awt.Dimension;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import static com.elle.elle_gui.miscellaneous.TableConstants.*;
import javax.swing.JFrame;
/**
 *
 * @author fuxiaoqian
 */
public class ViewATradeWindow extends javax.swing.JFrame {
    
    private ATrade aTradeInView;
    private JFrame parent;
    String tableName;
    String title;
    /**
     * Creates new form SelectionRowView
     */
    public ViewATradeWindow(ATrade tradeInView, String tableName, JFrame parent) {
        this.tableName = tableName;
        setTitle();
        aTradeInView = tradeInView;
       
        initComponents();
        
        loadATradeToTable();
        
       this.parent = parent;  
        this.setPreferredSize(new Dimension(300, 600));
        this.setLocationRelativeTo(parent);
        
        Authorization.authorize(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aTradeScrollpane = new javax.swing.JScrollPane();
        aTradeTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(title);
        setName("viewATrade"); // NOI18N

        aTradeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        aTradeScrollpane.setViewportView(aTradeTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aTradeScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aTradeScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setTitle(){
        switch(tableName){
            case (POSITIONS_TABLE_NAME):
                title = "View Position";
                break;
            case(TRADES_TABLE_NAME):
                title = "View Trade";
                break;
            case(ALLOCATIONS_TABLE_NAME):
                title = "View Allocation";
                break;
            default:
                title = "View Record";
                break;
                
        }
    }
    
    public void loadATradeToTable(){
        Vector<String> aTradeColumnName = new Vector<String>();
        aTradeColumnName.addElement("field name");
        aTradeColumnName.addElement("field value");
        
        Vector<Vector> aTradeRowValue = aTradeInView.getRowData();
        
        DefaultTableModel tableModel = new DefaultTableModel(aTradeRowValue, aTradeColumnName);
        aTradeTable.setModel(tableModel);
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane aTradeScrollpane;
    private javax.swing.JTable aTradeTable;
    // End of variables declaration//GEN-END:variables
}
